import argparse
from os import path
import os
from datetime import date
from datetime import datetime
# Parse our Yaget game systems into c++ code using 'IDL'


#  --root=$(YAGET_ROOT_FOLDER) --configuration=$(Configuration) --destination=$(YAGET_RUN_FOLDER)

deployTag = 'DEPLOY'

def ConvertPath(path):
    return path.replace(os.path.sep, '/')

def main():

    global deployTag

    parser = argparse.ArgumentParser(description='''Parse 'IDL' (*.ygs) file  into it's C++ representation. Yaget (c)2022.
                                                   Sample input [$(YAGET_ROOT_FOLDER)\DevTools\ParseGameSystem\pgs.py --file=$(ProjectDir)$(TargetName).ygs]
                                                   expended to [c:\Development\yaget\DevTools\ParseGameSystem\pgs.py --file=C:\Development\yaget\branch\zloty\development\Tools\YagetEditor\source\Editor.ygs]''')

    parser.add_argument('-f', '--file', dest='file', required=True, help='Yaget Game System description file (IDL) location')
    parser.add_argument('-s', '--silent', action='store_true', help='Supress print statements (does not apply to --help or error messages')
    parser.add_argument('-t', '--test', action='store_true', help='Run through all steps but not actully update files, useful for diagnostics, checks')

    args = parser.parse_args()

    if args.test:
        deployTag = 'DEPLOY-TEST'

    if not path.isfile(args.file):
        print("[{}] INFO: YGS file '{}' does not exist, no conversion will be performed.".format(deployTag, ConvertPath(args.file)))
        exit(0)

    # create/update new file
    outputFileName = args.file + '.h'

    contents = None
    #if path.isfile(outputFileName):
        #with open(outputFileName) as f:
            #contents = f.read()

    if contents == None:
        today = date.today()

        contents =  '''/* File generated by ygs tool on ''' +  datetime.now().strftime("%d/%m/%Y at %I:%M:%S%p") + ''', do not manually modify. */
///////////////////////////////////////////////////////////////////////
// ''' + path.basename(outputFileName) +  '''
//
//  Copyright ''' + today.strftime("%m/%d/%Y") +  ''' Edgar Glowacki.
//
//  Maintained by: Edgar
//
//  NOTES:
//      file_notes_go_here
//
//
//  #include "''' + path.basename(outputFileName) +  '''"
//
//////////////////////////////////////////////////////////////////////
//! \\file
#pragma once

#include "YagetCore.h"
'''


    with open(outputFileName, 'w') as f:
        f.write(contents)




if __name__ == "__main__":
    main()
